### PR TITLE
Dweb demo

### PR DESCRIPTION
**Pull request by weswalla**
This PR combines aspects of Wes and Nick's work on the dashboard and assessment widget display.

___________________
From Wes:
[x] Assessment widget components
[x] Widget rendering in the dashboard
[x] Fixed package versions for profiles & neighbourhoods client which were breaking in develop
...

____________________
From Nick:
[x]  Feature: Assessment widget configuration after applet install, or by pressing the config button in top right of dashboard.

Following on from the last PR dashboard merge correcting...
[x] Fix: No value feeding through on resource tab
[x] Fix: Hard coded filtering by subjective/objective dimension to be changed to API call
Also
[x] Externalised nh style base components using neighbourhoods-design-system-components package
[x] Fixed issue with scoped-registry polyfill not actually being loaded, added hmr
[x] Removed unused columns on context pages

### CODE REVIEW

**Comment by adaburrows** [comment]
What is our criteria for when this gets merged into develop?

**Comment by nick-stebbings** [comment]
I would say... if the demo works!

I would recommend everyone just check this branch out now and take it for a spin for some pre-demo-demo's!
As far as I am concerned I am happy with completion of the new features added, although a few shortcuts were taken to patch things that might compromise the demo or that I didn't have time to fully style.

**Comment by pospi** [comment]
(just added myself as a review so I get pinged when this is merged)

**Comment by nick-stebbings** [comment]
Are we happy to merge this now, post demo?
My next PR is branching off this one for now.

**Comment by weswalla** [comment]
yeah I'd say so @nick-stebbings

**Pull request merged**
