### PR TITLE
Feature/78 no create neighbourhood validation

### LINKED ISSUE #78: There is no validation on the CreateNeighbourhood dialog
- Add yup validation schema
- Add UI elements to notify ( ask design team about specifics?) of validation status
- Make the image optional

### PR DESCRIPTION
**Pull request by nick-stebbings**
- nh-select-avatar now used. Avatar is no longer compulsory
- Default NH logo for select avatar
- Validation schema is added (no NH name less than 4 chars)
- Dialog button disabled when validation schema invalid (also there is the option to allow submit and trigger validation messages, we need to decide which is better UX)
- Tidy up and rename component

### CODE REVIEW

**Comment by adaburrows** [comment]
I'll approve and merge after the package.json is fixed.

**Comment by nick-stebbings** [comment]
> I'll approve and merge after the package.json is fixed.

Done.

**Comment by nick-stebbings** [comment]
re: " we need to decide which is better UX", I am going to coordinate with the design team to have a meeting and see what they think. I expect to change the code in here so that we have clear messages about what has gone wrong, and how these messages should appear. Feel like we need to set some standards on this before a lot more form making commences.
 @Kasimirsuterwinter  @herramienta-digital

**Comment by adaburrows** [comment]
@nick-stebbings , @Kasimirsuterwinter , @herramienta-digital , I can coordinate that. There's actually a lot on their plates right now. But I can bring it up as a priority. What we should probably do it just create or pull in something general enough for surfacing what went wrong and where it went wrong so we can implement whatever UX the design team thinks we should.

**Pull request merged**
