### PR TITLE
Feature/pnpm

### PR DESCRIPTION
**Pull request by pospi**
Implements #47 for this workspace.

Branching off WIP DWeb work for now but simple changes easily rebased onto `develop` if necessary.

### CODE REVIEW

**Comment by adaburrows** [comment]
I say go for it.

**Review by adaburrows — APPROVED** [review]

**Comment by nick-stebbings** [comment]
My only question was svelte meant to be added as a dependency? Otherwise all good, due to collate many features tomorrow into a big Pr for Dweb.  But it has almost all been seen by another dev and approved.

Bit of a scramble.. sorry.. ahem, agile approach

**Comment by pospi** [comment]
Yep, it's meant to be there.
One issue you get in migrating is that the NPM directory setup "shadows" missing dependencies in child modules, since they are also resolved in parent directories. With the content-addressable hardlinked `npm_modules` format that PNPM uses, dependencies must be explicitly listed as they won't be inherited from parent directories in this way.
So you get a few missing dependencies sometimes, often in test or workspace modules which aren't published to a registry since they never see use in an isolated directory.

**Comment by nick-stebbings** [comment]
Ok, makes sense! If it works it works.

**Comment by nick-stebbings** [comment]
I tested this but due to the little queue of merge requests ended up continuing to work and then to bundle it into a slightly bigger PR which includes this and other changes to the build scripts..
Will request review on that once I have worked out a couple of issues and hopefully we can clear the backlog

**Comment by nick-stebbings** [comment]
Merged in with #49

**Pull request closed without merging**
